// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBWr8noOtdAj4EdyCcB--cPTSUg6IhwKw',
    appId: '1:282840806459:web:18f515152b5d7d1c4f581e',
    messagingSenderId: '282840806459',
    projectId: 'restaurantec-bf5fb',
    authDomain: 'restaurantec-bf5fb.firebaseapp.com',
    storageBucket: 'restaurantec-bf5fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPlWG1NzNBap7LX8KclTdBxcl6bVUiCc',
    appId: '1:282840806459:android:238229e8310146804f581e',
    messagingSenderId: '282840806459',
    projectId: 'restaurantec-bf5fb',
    storageBucket: 'restaurantec-bf5fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbJq5blcdfdlEjfaXRfP9DLMceKw3d-k',
    appId: '1:282840806459:ios:b7942332a94f6c2e4f581e',
    messagingSenderId: '282840806459',
    projectId: 'restaurantec-bf5fb',
    storageBucket: 'restaurantec-bf5fb.appspot.com',
    iosBundleId: 'com.example.finanzasJohana',
  );
}
